name: CI - Build & Push Ollama

on:
  push:
    branches: ["main", "staging"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: noveriojoee/ollama-qwen3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: noveriojoee
          password: Testing12345

      - name: Build base image (no model baked)
        run: |
          docker build -t $IMAGE_NAME:base -f Dockerfile .

      - name: Start helper container
        run: |
          # keep container running to allow running `ollama pull` inside
          # the base image has an ENTRYPOINT of `ollama` so passing `sleep` without
          # overriding entrypoint causes `ollama sleep` (invalid). Clear entrypoint.
          docker run -d --entrypoint "" --name ollama-build $IMAGE_NAME:base sleep infinity || (
            echo "Failed to start helper container"; docker images --format 'table {{.Repository}}:{{.Tag}}\t{{.ID}}\t{{.Size}}'; exit 1)

      - name: Pull model inside container (retry)
        run: |
          set -e
          ATTEMPTS=3
          for i in $(seq 1 $ATTEMPTS); do
            echo "Attempt $i to pull qwen3 inside container..."
            if docker exec ollama-build ollama pull qwen3; then
              echo "Model pulled successfully"
              break
            fi
            if [ "$i" -eq "$ATTEMPTS" ]; then
              echo "Failed to pull model after $ATTEMPTS attempts"; docker logs ollama-build || true; exit 1
            fi
            sleep 5
          done

      - name: Commit container to image with model
        run: |
          docker commit ollama-build $IMAGE_NAME:with-model

      - name: Tag final image
        run: |
          docker tag $IMAGE_NAME:with-model $IMAGE_NAME:latest

      - name: Push final image to Docker Hub
        run: |
          docker push $IMAGE_NAME:latest

      - name: Cleanup
        if: always()
        run: |
          docker rm -f ollama-build || true
          docker image prune -af || true

      - name: Report
        run: echo "Pushed $IMAGE_NAME:latest"
